<?php

namespace AppBundle\Repository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Recherche du departement selon l'user
     *
     * @author: Delrodie AMOIKON
     * @version: v1.0
     * @version: 13/11/2017 19:07
     */
    public function getDepartementByUser($user)
    {
        return $qb = $this->createQueryBuilder('d')
                   ->innerJoin('d.gestionnaires', 'g')
                   ->innerJoin('g.user', 'u')
                   ->where('u.id = :user')
                   ->setParameter('user', $user);
    }

    /**
     * Liste des departements par type
     *
     * @author: Delrodie AMOIKON
     * @version: v1.0
     * @since: 12/11/2017 12:10
     */
    public function findListDistrict($type)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                          SELECT d
                          FROM AppBundle:Departement d
                          Where d.type LIKE :type
                          ORDER BY d.nom ASC
                      ')
                      ->setParameter('type', '%'.$type.'%')
                      ->getResult()
                      ;
    }
}
